### ISSUE TITLE
BEMCheckBoxGroup Header

### ISSUE THREAD

**Issue by Vortec4800** [Boris-Em/BEMCheckBox#43]
I'm using this with Carthage (not by choice) and it seems like the Framework Carthage generates doesn't have the Group header file. I'm not sure what the issue is, maybe it needs some configuration updates in the Framework's Xcode project?

**Comment by Boris-Em** [comment]
Thanks for opening this issue.
I think that the issue probably comes from the fact that I haven't released a new version with the Group features yet. They're therefore available on the `master` branch, but not on Cocoapods nor Carthage yet.

**Comment by Vortec4800** [comment]
Well we have our Carthage file set to use the `HEAD` on `master` so I don't think it's a version issue. I really think it's some sort of configuration issue, I just don't use Carthage enough to know what it is.

**Comment by Boris-Em** [comment]
Thanks for the feedback @Vortec4800. Let me take a look at that.

**Comment by Boris-Em** [comment]
I think that the issue comes from the fact that the header file for `BEMCheckBoxGroup` is not public.
I'll fix that later on today.

**Comment by Boris-Em** [comment]
I made a few changes that should solve the issue on the banch `bug/43Header`. Could you confirm that it works for you now from this branch @Vortec4800?

**Comment by Vortec4800** [comment]
That did the trick, I think you're good to merge it.

**Comment by Boris-Em** [comment]
Thanks for your help @Vortec4800!

**Comment by simonbromberg** [comment]
Still getting this. Installed via Cocoapods, showing versions 1.4.1. Xcode 8.3.3 (8E3004b)
